<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EI1MF8H" failures="1" tests="7" name="normalUser.LoginTest" time="51.113" errors="0" timestamp="2022-04-11T17:51:23 BDT" skipped="0">
  <testcase classname="normalUser.LoginTest" name="verifyElemntsOnPageTest" time="4.100"/>
  <system-out/>
  <testcase classname="normalUser.LoginTest" name="verifyLogin" time="9.034">
    <failure message="expected [https://dev.zntral.net/dashboarda] but found [https://dev.zntral.net/dashboard]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://dev.zntral.net/dashboarda] but found [https://dev.zntral.net/dashboard]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at normalUser.LoginTest.verifyLogin(LoginTest.java:113)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <system-out/>
  <testcase classname="normalUser.LoginTest" name="loginWithoutUsername" time="5.221"/>
  <system-out/>
  <testcase classname="normalUser.LoginTest" name="loginWithoutPassword" time="12.706"/>
  <system-out/>
  <testcase classname="normalUser.LoginTest" name="loginWithEmptyField" time="3.895"/>
  <system-out/>
  <testcase classname="normalUser.LoginTest" name="forgotPassword" time="6.814"/>
  <system-out/>
  <testcase classname="normalUser.LoginTest" name="randomInput" time="9.343"/>
  <system-out/>
</testsuite> <!-- normalUser.LoginTest -->
